Adjusted copy step and working directory

diff --git a/.github/workflows/generated-docs.yml b/.github/workflows/generated-docs.yml
--- a/.github/workflows/generated-docs.yml
+++ b/.github/workflows/generated-docs.yml
@@ -97,7 +97,14 @@ jobs:
           cp DESCRIPTION stochtree_cran/
           cp _pkgdown.yml stochtree_cran/
           cp R_README.md stochtree_cran/README.md
-          cp cran-bootstrap.R stochtree_cran/
+
+      - name: Verify Makevars File
+        working-directory: stochtree-repo
+        run: |
+          if [ ! -f stochtree_cran/src/Makevars ]; then
+            echo "Makevars file is missing in stochtree_cran/src/"
+            exit 1
+          fi
 
       - name: Install R Dependencies
         working-directory: stochtree-repo/stochtree_cran
@@ -111,7 +118,7 @@ jobs:
           Rscript -e 'if (!require("Rd2md")) { quit(status=1) }'
 
       - name: Run cran-bootstrap.R
-        working-directory: stochtree-repo/stochtree_cran
+        working-directory: stochtree-repo
         run: |
           Rscript cran-bootstrap.R
 
